### ISSUE TITLE
Support for 'docker' in 'options'

### ISSUE THREAD

**Issue by acederberg** [ktomk/pipelines#15]
Hi again @ktomk. Sorry for raising another issue. I found that the options section does nothing for my pipelines, e.g.

~~~yaml
image : node:16
options :
  docker : True
...
~~~

See for instance the `YAML`s in in #14. IDK if this is a big ask; my experiences make me imagine it might require some docker magic. I think I could do it by using a different image than the one I am using, but it is easier to just have it in options.

**Comment by ktomk** [comment]
It is certainly deaf b/c I always was under the impression that it does not make much of a difference when running locally (and never needed it). Depending on what an option does (and what your setup is, IIRC your Operating System (OS) is Windows Subsystem for Linux (WSL) unspecified version) and what you're trying to achieve this may require some action.

If you share a bit more context it might be possible to just check whats needed here. It's normally not much of an issue to add some docker magic as long as we're well with testing/reproducing.

And it might require the mojo indeed as not everything can be controlled with the image alone. So just let me know what this is for and I can share more feedback. @acederberg

**Comment by ktomk** [comment]
I've reviewed

~~~
options:
  docker: true
~~~

a bit more. From what I read from _[Run Docker commands in Bitbucket Pipelines (Bitbucket Support)](https://support.atlassian.com/bitbucket-cloud/docs/run-docker-commands-in-bitbucket-pipelines/)_ it enables access to Docker on their platform:

> To enable access to Docker daemon, you can either add `docker` as a service on the step (recommended), or add the global option in your `bitbucket-pipelines.yml`.

The good news: The first and recommended option (`docker` as a service) should already work in pipelines. Some details:

> As a special feature and by default pipelines mounts the docker socket into each container (on systems where the socket is available). This allows to launch pipelines from a pipeline as long as `pipelines` and the Docker client is available in the pipelines' container. `pipelines` will take care of the Docker client as `/usr/bin/docker` as long as the pipeline has the docker service (`services: [docker]`).

(refs [Pipelines inside Pipeline (Pipelines Read Me)](https://ktomk.github.io/pipelines/index.html#pipelines-inside-pipeline))

Please give it a try for the step(s) in question if you have not yet.

When that already works on your end then what would be left is to enable it as well if the global option is set. So in the best scenario, the docker magic is already in, only pipelines is not processing the global option yet.

Please confirm that adding the `docker` service in each step provides the functionality you're looking for already. Because if it does not, then there is as well a different issue than just parsing the global `docker` option and it must be addressed. @acederberg

**Comment by ktomk** [comment]
There is a new development version that has the global docker option supported: `dev-test-issue-15`, which already looks promising:

~~~
$ bin/pipelines --file test/data/yml/options.yml
+++ step #1

    name...........: (unnamed)
    effective-image: ktomk/pipelines:busybox
    container......: pipelines-1.no-name.default.pipelines
    container-id...: bb3ed4fc9853

+++ copying files into container...


+ docker --version
Docker version 19.03.1, build 74b1e89e8a
~~~

**Comment by ktomk** [comment]
just releases 0.0.64 with support for `options: {docker: true}` (global docker option).

please let me know if this already works towards your request, I'll leave this issue #15 open for that @acederberg

**Comment by acederberg** [comment]
@ktomk I'll give it a shot soon. Been swamped, I'll give it a try as soon as possible and let you know what happens. Sorry for the extremely late reply

**Comment by acederberg** [comment]
@ktomk Works great! The only thing I would like to add is that you probably want to run this on a socket that you aren't using for your development containers as you can end up with naming conflicts in networks, volumes, etc. 

Another thing is that any docker items ( e.g. networks, containers, volumes ) built in the pipeline aren't removed after the pipeline stops, though this should just be part of the pipeline steps really. Of course, build minutes could be saved without these steps.

Also this speeds things up significantly due to caching on image pulls. Thanks again!

**Comment by ktomk** [comment]
> I would like to add is that you probably want to run this on a socket that you aren't using for your development containers as you can end up with naming conflicts in networks, volumes, etc.

Can you elaborate a bit on this? Do you want to use a different socket? On the host or within the container? Or both?

There is a setting and IIRC there is also environment variable parsing but most likely this can be improved or at least tweaked for better usage.

Or is this about the network? Currently `pipelines` is using `--net local` IIRC, because that comes close to how it's on Bitbucket - 127.0.0.1 resolves to the running environment - if this is otherwise possible with a different docker networking, then I'd consider that, especially to give this granularity on a per-project level @acederberg .

And great to read this already solved it for you!

**Comment by acederberg** [comment]
@ktomk I was thinking of using a socket on a (fresh ) VM on my desktop with docker installed so that the environment is isolated and I don't have to remove any existing containers/volumes/networks. I'm not too sure about the technical details in regard to this, but I assume it won't be anything crazy (and that it is at all possible). I would mount this VM socket in the container running the `steps`, where the container runs on the host, for instance. So a docker container running on one socket using a different socket to execute docker commands.

Of course I could just do everything on the VM and drastically simplify the situation.

**Comment by ktomk** [comment]
That sounds interesting but I'm not sure if I understand the use-case clearly.

> have to remove any existing containers/volumes/networks

Perhaps you mean that everything is shared locally (existing networks should not be a concern, as pipelines uses `--net local`  and this then would be more than "just" docker networks). Containers and Volumes are shared as (which is normally a benefit to get things up speed).

An existing feature that can be used to have a bit more isolation on the same host is Rootless, see [How-To Rootless Pipelines](https://ktomk.github.io/pipelines/doc/PIPELINES-HOWTO-ROOTLESS.html) - just to point to an existing option that may already work and is also quite a good test-case locally.

And for existing configuration parameters see [Configuration Parameters](https://ktomk.github.io/pipelines/doc/CONFIGURATION-PARAMETERS.html), not that I think it is possible with the existing options, but maybe it helps to learn about those (and/or proposing a new setting that might help doing this).

(likely requires a new setting, `docker.socket.src-path`, explicitly specifying the source path of the docker socket mount point and then something to control the socket to run the services with, `docker.socket.services` ... but without proper understanding me is a bag of cats right now and also someone asked for running pipelines from a docker container [but with project at host] and that use-case should not be easily disregarded as well)
