### ISSUE TITLE
Failed to parse validated YAML file

### ISSUE THREAD

**Issue by adimoi** [ktomk/pipelines#16]
The following simple `bitbucket-pipelines.yml` is rejected with "_verify the file contains valid YAML: Unable to parse at line 2 (near "sleep 10;")._"

~~~
.test-sleep: &test-sleep
  sleep 10;
  sleep 20;
  
.test-step: &test-sleep-step
  step:
    name: Simple Test
    script:
      - date;
      - *test-sleep
      - date;

pipelines:
  default:
    - parallel:
        - <<: *test-sleep-step
~~~

This file was validated by https://yamlchecker.com/ and https://bitbucket-pipelines.atlassian.io/validator and  executes properly in Atlassian Bitbucket Pipelines.

[bitbucket-pipelines.zip](https://github.com/ktomk/pipelines/files/8633095/bitbucket-pipelines.zip)

**Comment by ktomk** [comment]
Yes, this is rather awkward and is caused by the parser that ships with pipelines itself. I see two options here:

1. install the PHP YAML extension - if available it will be used and works on your YAML

3. slightly modify the YAML, e.g. you could write the two commands on a single line:

~~~
.test-sleep: &test-sleep
  sleep 10; sleep 20;
~~~
(the newline is folded into space with the original as well)

or use `|`:

~~~
.test-sleep: &test-sleep |
  sleep 10;
  sleep 20;
~~~
(this adds new-lines but should not become a problem within the script, I'd prefer the first thought)

Thanks for providing the example. @adimoi

**Comment by adimoi** [comment]
I've used your first recommendation
```
.test-sleep: &test-sleep
  sleep 10; sleep 20;
```
Thanks!
