### ISSUE TITLE
Mounting Local Volumes to allow application to access local files

### ISSUE THREAD

**Issue by pparchure** [ktomk/pipelines#2]
Hello Sir,
I have been using your pipeline package to run my yaml.file
My application needs to access certain files on the local machine, which it cannot do unless a volume has been mounted. 
I can see some functionality  --mount in your readme, but I am not sure how to use it to mount certain volumes to allow my application to interact with it. 
Could you please help me with this. I dont want to keep every file in the application working directory.

Thank you.

**Comment by ktomk** [comment]
I don't know about the `--mount` switch and for what you're trying to do it sounds like that pipelines is not that well fitting for your use case, it operates on the application working (project) directory.

Instead of using pipelines, you can use docker directly. To make that easier to use, one suggestion is to use a shell script as a docker command line can grow a bit longer and you might want to call some more docker commands after each other.

If you want to get some inspiration running pipelines with the `--verbose` and `--dry-run` switches will show you the docker commands pipelines would have been used..

**Comment by ktomk** [comment]
@pparchure This still is an issue for you?
